### ISSUE TITLE
为毛我的github里面的repo列表会有你这个项目？

### ISSUE THREAD

**Issue by yidao620c** [jjeejj/jjeejj.github.io#64]
一直搞不懂为什么
![image](https://user-images.githubusercontent.com/1510785/45129843-9fecdf80-b1b8-11e8-99b0-aa9b6dbf3bdc.png)

**Comment by jjeejj** [comment]
@yidao620c  我的也会有别人的。 这个好像 github 根据某种条件推荐的

**Comment by yidao620c** [comment]
哈哈，我要怎么删了那个记录呀，看着真是不爽

**Comment by yidao620c** [comment]
我要投诉

**Comment by yidao620c** [comment]
为什么要推荐你，而不是推荐个妹子？

**Comment by jjeejj** [comment]
。。。。。。 这个我也不知道。关了哈。你想删除的话那你在琢磨琢磨，或者问问github官方
